### ISSUE TITLE
Improve Pairing experience

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/Calliope-Android-App#11]
## Issue
While pairing there is a step, where the user has to wait for the pairing dialogue, but nothing visually shows him what actually is going on and what he has to do.

## Proposed solution
Where in the current situation there is the step "WAIT" (see reprocution below) there should be additional hints that visuallize for the user what is going on:

- Showing a dialogue, that tells to wait for the pairing request?
- Showing a hint, that after the pairing was sucessfull the calliope need a long time to reboot or that asks the user to press on reset on the calliope to continue?
- Give a more clear information about the current progress:
  - is the App currently trying to bond?
  - Was the bonding a suiccess?
  - Was it a failure?
- The floating action button should indicate more clearly if there is a device available and bonded or if there isnt.

#### mini 3
Make sure to have a program with active Bluetooth on the mini. That could be any program from MakeCode compiled for the mini 3 without any changes (e.g. loading the Radio or JacDac extension will disable Bluetetooth)
#### mini 1 and mini 2
Make sure to have a program with active Bluetooth and proper Bluetooth settings. This could be a program from MakeCode where the extension »one-time-pairing« is included.

#### On your android device
Make sure to remove any bonding for the Calliope you want to pair in the Bluetooth settings of your device. It might also help to get a clean start to delete the app cache storage from the App Info.

### Pairing
- Boot the Calliope mini in DFU mode (showing the Bluetooth pattern) by pressing AB+Reset or Tripple-Reset (mini 3)
- Tab on the floating action button and open the pattern dialogue
- Draw the pattern
- Tab on the Green button showing sowing the sinus-icon or on "yes", depending on what you see
- The popup closes.
- **WAIT**
- The device will ask you to confirm the pairing. Open the dialogue and confirm.
- The Calliope will show a checkmark on its screen.
- Press reset on the calliope or wait for the calliope to reset automatically (can take some time)

If the calliope shows a cross on the screen there was an issue while pairing. Try again by starting with "_Boot the Calliope mini in DFU mode_"

https://github.com/calliope-edu/Calliope-Android-App/assets/3764089/528f66a1-145d-49bb-8697-e732bf765539

**Comment by Tsisar** [comment]
Information about the progress of the connection is displayed more clearly. 
Do we need to add information about the installation of extensions directly to the program?

**Comment by fabianhugo** [comment]
good idea, could be a feature for future versions to display information about extensions (radio, etc). but for now its good.
