### ISSUE TITLE
Improve transfer experience

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/Calliope-Android-App#14]
## Issue

The time between pressing the download button and a visuall response seems to long.

## Proposed solution:

- Turning the floating action button from green to blue imediately after a download is recognized.
- Make it visually more clear if something fails (e.g. showing a toast if the process stops/fails and turn the floating button red for a moment)
  - A common case of failure might be if you try to flash a v3 program on a v2. At the moment there is no visuall hint for the failure, just the fact, that the floating button does not turn blue a few seconds after you pressed the download button and the green toast epeared.

https://github.com/calliope-edu/Calliope-Android-App/assets/3764089/80d98f48-56cd-46a0-9878-6ff156e11c72

**Comment by Tsisar** [comment]
When waiting for the connection, the key changes color to yellow, after the firmware starts, it changes to blue.

**Comment by fabianhugo** [comment]
the transfer experience is improved, great!
