### ISSUE TITLE
When connecting Calliope mini V3 wrong version is shown

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/Calliope-Android-App#17]
When I connect to a Calliope mini V3 the App shows Calliope mini V2 connected. It should be the correct version – or even better, just show "Calliope mini connected" or in German "Calliope mini verbunden".

**Comment by Tsisar** [comment]
Fixed:
```
Mini version %s connected/Mini-Version %s verbunden
1 or 2/1 oder 2
3/3
```

**Comment by joernalraun** [comment]
Great! However, please use always "Calliope mini" in all text strings... ;)

**Comment by Tsisar** [comment]
Ok. Done.
