### ISSUE TITLE
Floating Action Button Coloring

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/Calliope-Android-App#19]
right now, the floating action button does not react to errors with a red color but stays the same/green.

**Comment by fabianhugo** [comment]
floating action button:
default color: blue green/ turquoise 
successful connection: bright green
when flashing: blue
waiting (initialization.. ): yellow 
error: red

**Comment by Tsisar** [comment]
The button changes color to red in case of connection errors. 
In case of errors in operation, provided that it does not affect the connection, the button remains green.
