### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [calliope-edu/Calliope-Android-App#2]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, text overlap with icon. I think it may be an adaptation problem.
App version is 1.0.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, _**font size and display size**_ are the **_largest_** ! ! !, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![bug-mini_7](https://user-images.githubusercontent.com/18572115/103095548-e8579200-463b-11eb-9c5d-5d48a1003289.png)

**Comment by Amerlander** [comment]
Thank you, I will look into this for the next update. I think a compressed logo as well as removing the text "Flash your programs to your mini!" might help saving space for large font sizes or small screens.
On 24.12.2020 16:01:49, Franklinliu <notifications@github.com> wrote:
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, text overlap with icon. I think it may be an adaptation problem.
App version is 1.0.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, font size and display size are the largest ! ! !, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
[bug-mini_7] [https://user-images.githubusercontent.com/18572115/103095548-e8579200-463b-11eb-9c5d-5d48a1003289.png]

**Comment by Amerlander** [comment]
Should be fixed now with the latest release (1.1.1). Sorry for that long response time.
I'm happy to receive feedback, if this works for your devices!
