### ISSUE TITLE
"V1" or "without active BLE" Experience

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/Calliope-Android-App#24]
When a calliope mini 1 OR a mini 2/3 with disabled BLE (e.g. when Radio extension is loaded) gets flashed the user has to get the Calliope into DFU mode.

If the user forgets to do this the app will "wait" for the Calliope to show up. So a user can start the download and nothing happens, until he presses AB+Rest / 3xReset.

The overall behaviour is great, but the App should help to remember the user to start DFU mode, if it fails to start the programming imediately. 
Like getting a popup "_The App is not able to start flashing. It could be, that you are trying to programm a mini that has not enabled BLE by default. Try to get your device into DFU mode by pressing AB+Reset (mini 1/2) or 3 times reset (mini 3) to start BLE manually._"

**Comment by Tsisar** [comment]
We need to discuss this. By default, we have a connection timeout, we can't influence it, we have to wait until android tries to connect the mini

**Comment by Amerlander** [comment]
# V1 and V2
> Is the mini in bluetooth mode? 
> Try AB + Reset

# V3
> Is the mini in bluetooth mode? 
> Try tripple Reset

**Comment by joernalraun** [comment]
V1 and V2

Is the Calliope mini in Bluetooth mode?
Try AB + a short press as well on Reset

V3
Is the Calliope mini in Bluetooth mode?
Try pressing three times Reset

**Comment by Tsisar** [comment]
[Add 10-second connection timeout with notifiation for BLE service](https://github.com/calliope-edu/Calliope-Android-App/commit/6aefd8439494d99022092798b3c81cacdd6f131d)
