### ISSUE TITLE
Change pattern between bonded devices requires repairing

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/Calliope-Android-App#25]
When working with multiple Calliopes there is an issue when drawing the pattern to switch from second back to first device:

1. Draw pattern for first device and pair
2. Take second device, draw pattern and pair
3. Now change the pattern back to first device.
4. The app will show "connected to xx" and provide the option to "Remove"
5. As we want to use the device, we are not going to remove the deivce, but just close the pattern dialogue.
6. The App now keeps the connection to second device and not as the user idents first device When he tries to flash he might get version errors when device 1 and 2 are not the same version.
7. When opening the pattern again it changed back to second device.

It should be possible to change the pattern and if the device is a already bonded device the app should automatically switch to have the device selected that fits to the pattern input.

**Comment by Tsisar** [comment]
You cannot switch to a device by closing the dialog. It doesn't work that way. According to the rules of good code, if you click outside the dialog, you close it without saving your changes. It works like a "cancel" button.

**Comment by Amerlander** [comment]
We can have two buttons:
- Kepp "Remove"
- Add new button "Select"
